### ISSUE TITLE
Camera timestamp is wrong

### ISSUE THREAD

**Issue by terakoji** [ros-simulation/gazebo_ros_pkgs#564] opened 2017-04-18 22:55 UTC
On indigo-devel, I seem the timestamp of camera is wrong from PR   #551. Is it correct for Gazebo version 2? Previously my camera synchronized joint_state timestamp from gazebo_ros_controllers(2.4.11). On version 2.4.13 the timestamp of camera is seem the one before one frame.

**Comment by kev-the-dev** [comment] 2018-06-18 20:41
duplicate of #408, which has been fixed

**Closed as completed by kev-the-dev** 2018-06-18 20:41 UTC
