### ISSUE TITLE
installing ros-melodic-gazebo-ros in arch linux

### ISSUE THREAD

**Issue by G-Pereira** [ros-simulation/gazebo_ros_pkgs#791] opened 2018-08-07 00:16 UTC
https://pastebin.com/msqJenJH

Seems a problem with protoc.
Please don't say you don't support Arch Linux :)
Help me please

**Comment by G-Pereira** [comment] 2018-08-07 00:19
I have gazebo 9.3.0 and the ignition packages in the latest version:
ignition-common 1.1.1
ignition-math 4.0.0
ignition-fuel_tools 1.2.0

**Comment by chapulina** [comment] 2018-08-07 00:28
Seems to be the same as [this upstream issue](https://bitbucket.org/osrf/gazebo/issues/2496/protobuf-error-on-ubuntu-1804). I'll close this issue since the problem is not on this package, but on Gazebo. Please follow-up on that issue.

**Closed as completed by chapulina** 2018-08-07 00:28 UTC
