### ISSUE TITLE
gazebo_ros libgazebo_ros_api_plugin suffix incorrect on OS X

### ISSUE THREAD

**Issue by randvoorhies** [ros-simulation/gazebo_ros_pkgs#158] opened 2014-01-20 02:40 UTC
Gazebo fails to launch through roslaunch on OS X (e.g. with `roslaunch gazebo_ros empty_world.launch`), giving the following set of errors:

``` Shell
rand@Randolphs-MacBook-Pro:~/ros_catkin_ws/install_isolated/share/gazebo_ros/launch$ rosrun gazebo_ros gazebo
Could not find any path, checked the following paths:
/Users/rand/ros_catkin_ws/install_isolated/etc/libgazebo_ros_paths_plugin.so
/Users/rand/ros_catkin_ws/install_isolated/include/libgazebo_ros_paths_plugin.so
/Users/rand/ros_catkin_ws/install_isolated/lib/libgazebo_ros_paths_plugin.so
/Users/rand/ros_catkin_ws/install_isolated/share/libgazebo_ros_paths_plugin.so
Could not find any path, checked the following paths:
/Users/rand/ros_catkin_ws/install_isolated/etc/libgazebo_ros_api_plugin.so
/Users/rand/ros_catkin_ws/install_isolated/include/libgazebo_ros_api_plugin.so
/Users/rand/ros_catkin_ws/install_isolated/lib/libgazebo_ros_api_plugin.so
/Users/rand/ros_catkin_ws/install_isolated/share/libgazebo_ros_api_plugin.so
Could not find any path, checked the following paths:
/Users/rand/ros_catkin_ws/install_isolated/etc/libgazebo_ros_paths_plugin.so
/Users/rand/ros_catkin_ws/install_isolated/include/libgazebo_ros_paths_plugin.so
/Users/rand/ros_catkin_ws/install_isolated/lib/libgazebo_ros_paths_plugin.so
/Users/rand/ros_catkin_ws/install_isolated/share/libgazebo_ros_paths_plugin.so
Error. Invalid arguments
Error. Gui Invalid arguments
/Users/rand/ros_catkin_ws/install_isolated/lib/gazebo_ros/gazebo: line 25: kill: SIGINT: invalid signal specification
```

This is because the shared library suffix on OS X is `.dylib` instead of `.so`. Simply changing this in the gazebo script fixes this for me, but it would be nice if the scrips would check to see what suffix to use.

For example, this would fix the gazebo script:

``` bash
#!/bin/sh
final="$@"

# Check to see what shared library suffix to use
shext="so"
if [[ "$OSTYPE" == "darwin"* ]]; then
  shext="dylib"
fi

# add ros path plugin if it does not already exist in the passed in arguments
if [ `expr "$final" : ".*libgazebo_ros_paths_plugin\.$shext.*"` -eq 0 ]
then
    final="$final -s `catkin_find --first-only libgazebo_ros_paths_plugin.$shext`"
fi

# add ros api plugin if it does not already exist in the passed in arguments
if [ `expr "$final" : ".*libgazebo\_ros\_api\_plugin\.$shext*"` -eq 0 ]
then
    final="$final -s `catkin_find --first-only libgazebo_ros_api_plugin.$shext`"
fi

client_final="-g `catkin_find --first-only libgazebo_ros_paths_plugin.$shext`"

# Combine the commands
setup_path=$(pkg-config --variable=prefix gazebo)/share/gazebo/
. $setup_path/setup.sh 
gzserver $final & 
gzclient $client_final

# Kill the server
kill -s SIGINT $!
```

**Comment by traversaro** [comment] 2014-01-20 08:11
Are you sure that the correct way is to force the .so suffix? Apparently the correct way of compiling runtime-loadable code is to use MODULE instead of SHARED in CMakeLists add_library, that accidentally on OS X produces files with .so suffix.
Check https://bitbucket.org/osrf/gazebo/issue/800/plugin-loading-on-os-x#comment-5979548 for the related Gazebo bug.

**Comment by scpeters** [comment] 2014-01-21 18:34
See also the [gazebo issue](https://bitbucket.org/osrf/gazebo/issue/800/plugin-loading-on-os-x). We definitely want to fix this upstream as well.

**Comment by j-rivero** [comment] 2016-04-26 22:58
I think that the problem was fixed in gazebo some time ago, although the issue is still open since the fix seems not be so the best one.

Please reopen if you see something more that we need to do in this software.

**Closed as completed** 2016-04-26 23:01 UTC
