### ISSUE TITLE
gazebo_plugins: gazebo_ros_openni_kinect plugin not publishing depth and rgb camera info

### ISSUE THREAD

**Issue by bit-pirate** [ros-simulation/gazebo_ros_pkgs#95] opened 2013-08-01 03:31 UTC
I believe the important function to publish the camera info is

```
GazeboRosOpenniKinect::PublishCameraInfo()
```

However, I don't see anything calling it ever, which might be the cause of this issue.
For testing I have added a call of this function in `OnNewDepthFrame()`, but I am not sure this is the right place.

**Comment by bit-pirate** [comment] 2013-08-01 05:16
Once we find a solution for this, I can add it to my pull request https://github.com/ros-simulation/gazebo_ros_pkgs/pull/96.

**Comment by piyushk** [comment] 2013-08-06 21:37
This was originally fixed in https://code.ros.org/trac/ros-pkg/ticket/5596, but somehow got reverted in https://github.com/ros-simulation/gazebo_ros_pkgs/commit/0696de61c3a4ff58f202a81c31ab840774e6ab

Simply re-implementing my original patch did nothing, and I'll dig deeper into the code later tonight.

**Comment by piyushk** [comment] 2013-08-06 21:53
Here's the cause: https://github.com/ros-simulation/gazebo_ros_pkgs/commit/0696de61c3a4ff58f202a81c31ab840774e6ab#L11L555 

This worked because originally the function was virtual and called by the base class, a call that has now been removed. I believe your method of calling it in `OnNewDepthFrame()` is probably best. A bit more code is needed to ensure that subscribers to only the camera_info message receive it.

**Comment by bit-pirate** [comment] 2013-08-07 00:24
That should be ensured, since `PublishCameraInfo()` has its own subscriber counter and publisher. It would also be called outside the subscriber checks for the depth image, point cloud and image streams and hence would always be called when a new depth frame arrives.

Only minor back draw is, that the camera info cannot be published at a rate higher than the sensor's update rate. The inverse - camera info publishing rate < depth image publishing rate - however works.

**Comment by davetcoleman** [comment] 2013-08-07 01:36
Commit https://github.com/ros-simulation/gazebo_ros_pkgs/commit/0696de61c3a4ff58f202a81c31ab840774e6ab#L11L555 was me syncing the updates from the DRC Virtual Robotics Challenge code base back into the main gazebo repository. I did not remove that line myself so am not sure why it was removed, but @hsu probably knows why it was deleted.

**Closed as completed** 2013-08-09 19:44 UTC

**Comment by bit-pirate** [comment] 2013-08-13 00:37
Could someone re-release gazebo pkgs with this fix? Thanks!

**Comment by davetcoleman** [comment] 2013-08-13 01:43
Will do.

**Comment by davetcoleman** [comment] 2013-08-13 03:21
https://github.com/ros/rosdistro/pull/1702
