### ISSUE TITLE
gazebo_ros_control: joint-specific information and actuator-specific information

### ISSUE THREAD

**Issue by jbohren** [ros-simulation/gazebo_ros_pkgs#52] opened 2013-06-26 17:06 UTC
As of the recent merge of PR #46, the ros_control plugin is informed of the joints it should control by `<actuator>` tags in the XDF and then the API constructs `JointData` structures for each joint. I feel like some of the information is muddled here between joint-specific information, actuator-specific information, and transmission-specific information. 

One thing that I find a bit confusing is whether or not we're assuming joint-level control or actuator control. From my perspective, it looks like if you're using <transmission> tags then you're assuming you have actuator-level control, and you need to convert from joint-space to actuator-space. 

But now, even if you have joint-level control (gazebo API and many common C++ hardware APIs) you still need to have `<transmission>` and you classify each of them as a `SimpleTransmission` even though there might be a non-trivial transmission which is accounted for by a lower-level system.

@adolfo-rt @davetcoleman

**Comment by davetcoleman** [comment] 2013-06-26 18:58
My intention was to have users start using the more-powerful `<transmission>` elements so that in the future we can expand the plugin to actually use transmissions and handle actuators properly. I realize the implementation right now is kind of awkward but I don't have time right now to focus on all the extra features that I do not currently need. Feel free to add these features though!

I'm not happy with the `JointData` structures either, but I needed to pass this information somehow and doing a quick search of ros_control I didn't see something that accomplished this exactly. I intend for this struct to change in the future.

However, the muddling of joint-level control and actuator control doesn't seem to be that bad to me since all of this after all is using Gazebo. 

How exactly would you change it?

**Comment by adolfo-rt** [comment] 2013-06-27 07:46
As discussed [here](https://github.com/jhu-lcsr/ros_control_gazebo/issues/7#issuecomment-19189051), it needs to be decided whether gazebo_ros_control should know about transmissions and actuators or not. The current work suggests that the idea is to indeed excersise them in simulation as well. I say +1 to this, as it will allow to represent some underactuated mechanisms through transmissions.

Regarding the specification of hardware interfaces, 

**Fully actuated** transmissions don't require to separately specify hardware interfaces for actuators and joints, so the hardware interface could be a transmission-level property, specified only _once_, like so

``` xml
<transmission type="transmission_interface/SimpleTransmission" name="foo_trans">
  <joint name="foo_joint"/>
  <actuator name="foo_motor"/>
  <mechanicalReduction>50</mechanicalReduction>
  <hardwareInterface>EffortJointInterface</hardwareInterface>
  <hardwareInterface>VelocityJointInterface</hardwareInterface>
</transmission>
```

notice that in the example there are two hardwareInterface elements. This would represent an actuator that can be controlled in effort or velocity modes. It's a power user case, but we should allow it.

@davetcoleman Your current usecase fits nicely with this model. It feels awkward to only specify the hardware interface at the actuator level.

**Underactuated transmissions** are more complex and require specification of hardware interfaces on a per-joint and per-actuator basis. I expect these transmissions to show up much less frequently in practice. For them, we could use a specification like

``` xml
<transmission type="transmission_interface/UnderactTransmission" name="foo_trans">
  <joint name="foo_joint" hardwareInterface="EffortJointInterface"/>
  <joint name="bar_joint" hardwareInterface="JointStateInterface"/>
  <actuator name="foo_motor" hardwareInterface="EffortJointInterface"/>
  <mechanicalReduction>50</mechanicalReduction>
</transmission>
```

notice that `bar_joint` only has a `JointStateInterface`. These more complex specifications can come later on. In fact, the `transmissions_interface` package has no officially supported underactuated transmission.

**Comment by adolfo-rt** [comment] 2013-06-27 08:01
> I'm not happy with the JointData structures either, but I needed to pass this information somehow and doing a quick search of ros_control I didn't see something that accomplished this exactly. I intend for this struct to change in the future.

I'd be interested in discussing a more elegant design. Hopefully you can come up with a better solution than I did. These are the constraints that drove me to the current design:
- We cannot use the existing (read-only) `[Joint|Actuator]StateInterface` classes, because we need read/write access to the variables. **Consequence:** We need to create a new set of raw-data wrappers: `[Joint|Actuator]Data`.
- Mapping a single variable through a transmission (eg. actuator to joint position) might not only require access to position variables, but also others such as effort. This is especially true for underactuated transmissions. **Consequence**: `[Joint|Actuator]Data` wrap the complete state, pos, vel, eff. You only should populate the fileds you're interested in.

I admit that allowing underactuated transmissions make the whole thing more complex, and I haven't come up with a better compromise between the desired feature set and usability. The first iteration of the transmissions interface only allowed fully-actuated transmissions and had a terser API, ie. `[Joint|Actuator]Data` didn't exist.

**Comment by davetcoleman** [comment] 2013-06-27 18:07
I'd like to use a <transmission> XML specification that allows for future implementation of under-actuated systems, so I'd like to get this figured out if possible!

In your **fully actuated** example you use

```
  <hardwareInterface>EffortJointInterface</hardwareInterface>
```

whereas in your **under actuated** example you specify the hardware interfaces as an attribute in the `<joint>` and `<actuator>`. I propose for consistency in fully actuated transmissions we also set this property as an attribute for one of the elements, I vote we put it in the `<actuator>` element and leave the `<joint>` element w/o a hardwareInterface attribute. Does this work?

For your `under actuated` example of

```
<transmission type="transmission_interface/UnderactTransmission" name="foo_trans">
  <joint name="foo_joint" hardwareInterface="EffortJointInterface"/>
  <joint name="bar_joint" hardwareInterface="JointStateInterface"/>
  <actuator name="foo_motor" hardwareInterface="EffortJointInterface"/>
  <mechanicalReduction>50</mechanicalReduction>
</transmission>
```

I don't understand what scenario you would have two joints with different hardware interfaces with the same actuator. Can you explain a better use case or maybe even an image? Would the two joints perhaps have different mechanical reductions?

> We need to create a new set of raw-data wrappers:

Don't we have enough wrappers in ros_control already? I fear we are making too many layers. Can we just make the `[Joint|Actuator]StateInterface` non-read-only? I'll admit I don't understand the consequences of all of this.

**Comment by jbohren** [comment] 2013-06-28 06:53
What do you guys think of something like the following, where we specify the relationships between joints and actuators directly and clearly in the [UR|S]DF xml:

**NOTE: I think the version in the following comment is better**

``` xml

<!-- Parallel Four-Bar Linkage -->

<joint name="horz_joint">...</joint>
<joint name="vert_joint">...</joint>
<joint name="vert_slave_joint">...</joint>
<joint name="horz_slave_joint">...</joint>

<transmission name="parallel" >

  <actuator name="horz_motor" type="hardware_interface/EffortJointInterface" />
  <actuator name="vert_motor" type="hardware_interface/EffortJointInterface" />

  <constraints>
    <!-- Equate the vertical motor to vertical joint, similarly for horizontal -->
    <!-- vert_joint = vert_motor -->
    <equality sum="0.0">
      <actuator name="vert_motor" scale="-1.0" />
      <joint name="vert_joint" />
    </equality>
    <equality sum="0.0">
      <actuator name="horz_motor" scale="-1.0"/>
      <joint name="horz_joint" />
    </equality>
    <!-- Constrain the link attached to  vert_slave_joint to stay parallel to vert_joint -->
    <!-- vert_slave_joint = horz_joint + vert_joint -->
    <equality sum="0.0">
      <joint name="vert_slave_joint" scale="-1.0"/>
      <joint name="horz_joint" />
      <joint name="vert_joint" />
    </equal>
    <!-- Constrain the link attached to horz_slave_joint to stay parallel to horz_joint -->
    <!-- horz_slave_joint = horz_joint - vert_joint -->
    <equality sum="0.0">
      <joint name="horz_slave_joint" scale="-1.0"/>
      <joint name="horz_joint" />
      <joint name="vert_joint" scale="-1.0" />
    </equal>
  </constraints>
</transmission>
```

``` xml
<!-- Under-Actuated Finger -->

<joint name="proximal_joint">...</joint>
<joint name="middle_joint">...</joint>
<joint name="distal_joint">...</joint>

<transmission name="finger">
  <actuator name="finger_motor" type="hardware_interface/EffortJointInterface"/>

  <constraints>
    <!-- Attach the proximal_joint to the motor directly -->
    <!-- proximal_joint = finger_motor -->
    <equality sum="0.0">
      <actuator name="finger_motor" scale="-1.0"/>
      <joint name="proximal_joint" />
    </equal>
    <!-- Drive the middle joint 1.2x the proximal joint, with a constant offset -->
    <!-- middle_joint = 1.2*proximal_joint + 0.1 -->
    <equality sum="0.1">
      <joint name="proximal_joint" scale="-1.2"/>
      <joint name="middle_joint" />
    </equal>
    <!-- Drive the middle joint 1.2x the proximal joint, with a constant offset -->
    <!-- distal_joint = 1.2*middle_joint + 0.1 -->
    <equality sum="0.1">
      <joint name="middle_joint" scale="-1.2"/>
      <joint name="distal_joint" />
    </equal>
  </constraints>
</transmission>
```

**Comment by jbohren** [comment] 2013-06-28 06:59
Or alternatively:

``` xml

<!-- Parallel Four-Bar Linkage -->

<joint name="horz_joint">...</joint>
<joint name="vert_joint">...</joint>
<joint name="vert_slave_joint">...</joint>
<joint name="horz_slave_joint">...</joint>

<transmission name="parallel" >

  <actuator name="horz_motor" type="hardware_interface/EffortJointInterface" />
  <actuator name="vert_motor" type="hardware_interface/EffortJointInterface" />

  <constraints>
    <!-- Equate the vertical motor to vertical joint, similarly for horizontal -->
    <!-- vert_joint = vert_motor -->
    <equality joint="vert_joint" offset="0.0">
      <actuator name="vert_motor" scale="1.0" />
    </equality>
    <equality joint="horz_joint" offset="0.0">
      <actuator name="horz_motor" scale="1.0"/>
    </equality>
    <!-- Constrain the link attached to  vert_slave_joint to stay parallel to vert_joint -->
    <!-- vert_slave_joint = horz_joint + vert_joint -->
    <equality joint="vert_slave_joint" offset="0.0">
      <joint name="horz_joint" />
      <joint name="vert_joint" />
    </equal>
    <!-- Constrain the link attached to horz_slave_joint to stay parallel to horz_joint -->
    <!-- horz_slave_joint = horz_joint - vert_joint -->
    <equality joint="horz_slave_joint" offset="0.0">
      <joint name="horz_joint" />
      <joint name="vert_joint" scale="-1.0" />
    </equal>
  </constraints>
</transmission>
```

``` xml
<!-- Under-Actuated Finger -->

<joint name="proximal_joint">...</joint>
<joint name="middle_joint">...</joint>
<joint name="distal_joint">...</joint>

<transmission name="finger">
  <actuator name="finger_motor" type="hardware_interface/EffortJointInterface"/>

  <constraints>
    <!-- Attach the proximal_joint to the motor directly -->
    <!-- proximal_joint = finger_motor -->
    <equality joint="proximal_joint" offset="0.0">
      <actuator name="finger_motor" scale="1.0"/>
    </equal>
    <!-- Drive the middle joint 1.2x the proximal joint, with a constant offset -->
    <!-- middle_joint = 1.2*proximal_joint + 0.1 -->
    <equality joint="middle_joint" offset="0.1">
      <joint name="proximal_joint" scale="1.2"/>
    </equal>
    <!-- Drive the middle joint 1.2x the proximal joint, with a constant offset -->
    <!-- distal_joint = 1.2*middle_joint + 0.1 -->
    <equality joint="distal_joint" offset="0.1">
      <joint name="middle_joint" scale="1.2"/>
    </equal>
  </constraints>
</transmission>
```

**Comment by adolfo-rt** [comment] 2013-06-28 09:06
Lots to reply to :)

Important terminology note: It's important to distinguish two cases of underactuated joints:
- **Fully-constrained:** The system has no free DOFs and the actuator commands are enough to reconstruct the state of all joints. I think @jbohren's 4-bar linkage and finger examples fall in this category. The URDF `<mimic>` tag actually implements such a transmission, and I think it should not even exist, as it's a very particular case that pollutes the URDF spec.
- **Under-constrained:** The system has free DOFs and apart from actuator commands, you need additional sensor input to reconstruct the state of the joints.  Many underactuated fingers (not Jon's example) are like this, where the closing sequence is affected by when and where contacts occur.

@davetcoleman, regarding where and how to specify hardware interfaces. Whatever we choose should adhere to the principle of least surprise to most users. Here's yet another proposal. It aims at generalizing what both you and I had previously suggested, and it's consistent across transmission types:
- If there are `<hardware_interface>` elements present all joints and actuators will register them by default, unless...
- A specific `<actuator>` or `<joint>` specifies hardware interfaces as an attribute, which takes precedence over (and ignores) the `<hardware_interface>` element.
- Corollary: If no `<hardware_interface>` element is present in a transmission spec, then all joints and actuators should specify them individually as attributes.

Example:

``` xml
<transmission type="transmission_interface/FingerTransmission" name="foo_trans">
  <joint name="f1_joint"/>
  <joint name="f2_joint" hardwareInterface="JointStateInterface"/>
  <joint name="f3_joint" hardwareInterface="JointStateInterface"/>
  <actuator name="finger_motor"/>
  <hardwareInterface>EffortJointInterface</hardwareInterface>
  <mechanicalReduction>50</mechanicalReduction>
</transmission>
```

Here the `finger_motor` actuator and `f1_joint` are effort-controlled, while `f2_joint` and `f3_joint` only report their state, but do not accept commands.

> Can we just make the [Joint|Actuator]StateInterface non-read-only?

It would break the semantics of the interface, which is explicitly read-only. This interface is meant to be used by controllers, and it does not make sense to allow writing into a read-only variable. Conversely, transmission interfaces are not meant to be used by controllers, hence are not exposed to them.

One comment about the `[Joint|Actuator]Data` structures. The transmission interface was designed with the idea that there will be an automatic robot model parser in place. No sane person should populate by hand a humanoid robot with half a hundred actuators and as many joints and transmissions. Considering that this should not be a user-facing feature, I'm not terribly concerned about it.

@jbohren Your 4-bar and finger examples are fully-constrained transmissions, and I don't think they will scale well to uderconstrained scenarios. If you need convincing, take a look at the PR2's gripper transmission; it has different implementations for the real and simulation scenarios (the simulation even has additional joints). I think we should let the plugin do the math. Encoding complex math expressions in XML is possible (see [MathML](http://en.wikipedia.org/wiki/MathML)), but IMO not meant for humans.

**Comment by jbohren** [comment] 2013-06-28 09:41
> @jbohren Your 4-bar and finger examples are fully-constrained transmissions, and I don't think they will scale well to uderconstrained scenarios. If you need convincing, take a look at the PR2's gripper transmission; it has different implementations for the real and simulation scenarios (the simulation even has additional joints). I think we should let the plugin do the math. Encoding complex math expressions in XML is possible (see MathML), but IMO not meant for humans.

@adolfo-rt In this case, yeah, they are fully constrained. But imagine instead of using an `<equality>` tag, you could specify an `<impedance>` tag (with stiffness and damping). In that case, you can start encoding the dynamics of a truly an underactuated finger directly in this form. 

With respect to MathML, that crossed my mind, and it took me all of five seconds before I decided that was not a good direction (you're right, definitely not meant for humans).

> ``` xml
> <transmission type="transmission_interface/FingerTransmission" name="foo_trans">
>   <joint name="f1_joint"/>
>   <joint name="f2_joint" hardwareInterface="JointStateInterface"/>
>   <joint name="f3_joint" hardwareInterface="JointStateInterface"/>
>   <actuator name="finger_motor"/>
>   <hardwareInterface>EffortJointInterface</hardwareInterface>
>   <mechanicalReduction>50</mechanicalReduction>
> </transmission>
> ```

My problem with schemas like the above is that when looking at it, it's not obvious to me at all which joints are actuated and how they are related to each-other. I'd like the look of the `<transmission>` tags to look more like the rest of URDF, where the kinematic and dynamic information is right there, and not very dependent on what kind of plugin you're loading.

**Comment by jbohren** [comment] 2013-06-28 09:45
Also, as an aside, I think I'd even want the `<actuator>` tags to be outside of the transmission, in the same scope as the `<joint>` and `<link>` tags. Then the `<transmission>` tags relate the `<actuator>` and `<joint>` together.

**Comment by jbohren** [comment] 2013-06-28 09:48
@adolfo-rt Also, for the more advanced underactuated finger example, consider an `<arclength>` constraint which could be used to apply tendon-like underconstrained underactuation.

**Comment by adolfo-rt** [comment] 2013-06-28 10:29
> My problem with schemas like the above is that when looking at it, it's not obvious to me at all which joints are actuated and how they are related to each-other. I'd like the look of the <transmission> tags to look more like the rest of URDF, where the kinematic and dynamic information is right there, and not very dependent on what kind of plugin you're loading.

This is the downside of having the transmission map implemented in code.

> Also, as an aside, I think I'd even want the <actuator> tags to be outside of the transmission, in the same scope as the <joint> and <link> tags. Then the <transmission> tags relate the <actuator> and <joint> together.

+1 to have actuators specified at the same level as joints and links. The implications to the URDF spec are greater for this case, and should be considered carefully. Since the transmission element already existed, and its internals have no predefined structure, I thought of this as the least-resistance path and took it.

As a personal opinion and small rant, I never really liked the URDF, when there were other specs out there with more critical mass, and able to deliver the desired feature set like Collada. Maybe there are compelling reasons to go for a custom format, but I am not aware of them. I applaud the OpenRAVE people for all their efforts to support Collada. That being said, I'm not very inclined to spend resources on modifying the URDF spec.

@jbohren Maybe it's possible to get away with a small set of constraints specified via XML to define the most common transmission types, I just don't have enough practical experience with the hard cases, and in real life vs. simulation to take sides. Still, the decision between plugins and XML constraints is not an XOR, both can exist. For instance, I think it will be easier on the eye (and to unerstand) to read that a transmission type is `Differential`, point to a plugin and just have to specify reduction ratios, than to go through a bunch of XML sums and products that in no way tell you that they represent a differential.

Let's not forget that most people will use very few common transmission types, which you can probably count  with the fingers of one hand. Those should have good out-of-the-box support (be it through plugins or XML constraints or whatever else). Let's concentrate on them, and decide how to best support them.

**Comment by jbohren** [comment] 2013-06-28 14:36
> @adolfo-rt  Maybe it's possible to get away with a small set of constraints specified via XML to define the most common transmission types, I just don't have enough practical experience with the hard cases, and in real life vs. simulation to take sides. Still, the decision between plugins and XML constraints is not an XOR, both can exist. For instance, I think it will be easier on the eye (and to unerstand) to read that a transmission type is Differential, point to a plugin and just have to specify reduction ratios, than to go through a bunch of XML sums and products that in no way tell you that they represent a differential.
> 
> Let's not forget that most people will use very few common transmission types, which you can probably count with the fingers of one hand. Those should have good out-of-the-box support (be it through plugins or XML constraints or whatever else). Let's concentrate on them, and decide how to best support them.

Yeah, these are definitely reasonable points. I see this discussion taking a while to come to a conclusion.

**Comment by davetcoleman** [comment] 2013-06-28 18:00
>  I just don't have enough practical experience with the hard cases, and in real life vs. simulation to take sides

Agreed

> Those should have good out-of-the-box support (be it through plugins or XML constraints or whatever else). Let's concentrate on them, and decide how to best support them.

This is my goal. Can't advanced use cases just use new/custom transmissions that maybe only work for that particular joint/actuator combination?

>  I think I'd even want the tags to be outside of the transmission.

My initial thinking was this, too, but after thinking about it further and talking to @hsu I decided there wasn't much usefulness to gain (other than semantic prettyness) but it requires that you duplicate the actuator tag and name for each actuator, further complicating the URDF spec. I agree with @adolfo-rt, `<transmission>` elements with actuator elements inside are the path of least resistance because they've been used before with the PR2. -1 on moving the actuator tag.

> My problem with schemas like the above is that when looking at it, it's not obvious to me at all which joints are actuated and how they are related to each-other. 

+1

> As a personal opinion and small rant, I never really liked the URDF, when there were other specs out there with more critical mass, and able to deliver the desired feature set like Collada. Maybe there are compelling reasons to go for a custom format, but I am not aware of them. I applaud the OpenRAVE people for all their efforts to support Collada. That being said, I'm not very inclined to spend resources on modifying the URDF spec.

Standardizing to Collada is good idea though I think that spec is fairly complex to make by hand. Food for thought: there are also some people who would like SDF to become the new URDF2.

**Final thoughts:** 
It seems to me we can skip the complicated transmission XML format debate by allowing each transmission type to define its own custom attributes and elements. The only thing we need to concern ourselves with at the moment is the base format that all transmissions should follow, from there you can add on whatever your application needs. The base case would be:

```
<transmission name="trans1" type="transmission_interface/SimpleTransmission">
  <joint name="joint1"/>
  <actuator name="motor1" hardwareInterface="EffortJointInterface" />
  <!-- transmission-specific properties here --> 
</transmission>
```

Remind me again, what is this missing?

**Comment by adolfo-rt** [comment] 2013-07-01 07:03
> > Those should have good out-of-the-box support (be it through plugins or XML constraints or whatever else). Let's concentrate on them, and decide how to best support them.
> 
> This is my goal. Can't advanced use cases just use new/custom transmissions that maybe only work for that particular joint/actuator combination?

Of course. There will surely be transmissions implementations that don't generalize beyond a specific piece of hardware.

> ``` xml
> <transmission name="trans1" type="transmission_interface/SimpleTransmission">
>   <joint name="joint1"/>
>   <actuator name="motor1" hardwareInterface="EffortJointInterface" />
>    
> </transmission>
> ```
> 
> Remind me again, what is this missing?

I never got any feedback from the proposal in [this comment](https://github.com/ros-simulation/gazebo_ros_pkgs/issues/52#issuecomment-20177634). The needed information is in place in your proposal, but my personal taste still favors a separate `<hardwareInterface>` element.

**Comment by davetcoleman** [comment] 2013-07-01 16:31
> - If there are <hardware_interface> elements present all joints and actuators will register them by default, unless...
> - A specific <actuator> or <joint> specifies hardware interfaces as an attribute, which takes precedence over (and ignores) the <hardware_interface> element.
> - Corollary: If no <hardware_interface> element is present in a transmission spec, then all joints and actuators should specify them individually as attributes.

Too me this is complicated - I think the part about "takes precedence over (and ignores) the `<hardware_interface>`" is non-intuitive. Having this attributes in different places allows for more than one way of setting up a transmission (confusing) and leads to invisible-to-the-user rules being relied on. 

Why not, for your example:

``` xml
<transmission type="transmission_interface/FingerTransmission" name="foo_trans">
  <joint name="f1_joint" hardwareInterface="EffortJointInterface" />
  <joint name="f2_joint" hardwareInterface="EffortJointInterface,JointStateInterface"/>
  <joint name="f3_joint" hardwareInterface="EffortJointInterface,JointStateInterface"/>
  <actuator name="finger_motor"/>
  <mechanicalReduction>50</mechanicalReduction>
</transmission>
```

?

**Comment by jbohren** [comment] 2013-07-01 16:42
@davetcoleman Yeah, I like how that's clearer. Maybe something more xml-y like this?

``` xml
<transmission type="transmission_interface/FingerTransmission" name="foo_trans">
  <joint name="f1_joint">
    <hardwareInterface type="EffortJointInterface"/>
    <JointStateInterface type="EffortJointInterface"/>
  </joint>
  <joint name="f2_joint">
    <hardwareInterface type="JointStateInterface"/>
  </joint>
  <joint name="f3_joint">
    <hardwareInterface type="JointStateInterface"/>
  </joint>
  <actuator name="finger_motor"/>
  <mechanicalReduction>50</mechanicalReduction>
</transmission>
```

One thing that would be nice is if it was made obvious by the XML what roles a given joint or actuator was playing in the transmission.

**Comment by adolfo-rt** [comment] 2013-07-02 08:27
> Why not, for your example:
> 
> ``` xml
> <transmission type="transmission_interface/FingerTransmission" name="foo_trans">
>   <joint name="f1_joint" hardwareInterface="EffortJointInterface" />
>   <joint name="f2_joint" hardwareInterface="EffortJointInterface,JointStateInterface"/>
>   <joint name="f3_joint" hardwareInterface="EffortJointInterface,JointStateInterface"/>
>   <actuator name="finger_motor"/>
>   <mechanicalReduction>50</mechanicalReduction>
> </transmission>
> ```

If `f1_joint`, `f2_joint`, and `f3_joint` have an `EffortJointInterface`, it means in principle that you can send independent control commands to each, which is not the case for an underactuated transmission. You can only send _one_ independent control command. Further, if the transmission is underconstrained, it might even be impossible to bring a joint to a certain configuration with control.

Deciding which joints to control is a tricky aspect of underconstrained mechanisms. In some cases it makes sense to expose the actuator as a joint to control.

So, getting back in track. It seems that both @davetcoleman and @jbohren prefer to not have the hardware interface as a separate element, so I give in. I'm also OK with the more XML-y syntax, which aligns with how the SDF was designed (try not to abuse XML attributes).

A simple, fully actuated transmission would then look like:

``` xml
<transmission type="transmission_interface/SimpleTransmission" name="simple_trans">
  <joint name="foo_joint"/>
  <actuator name="finger_motor">
    <hardwareInterface type="EffortJointInterface"/>
  </actuator>
  <mechanicalReduction>50</mechanicalReduction>
</transmission>
```

Concerning @jbohren's  concern about seeing roles represented. This _should_ be the case, and I lost track of this along the discussion. Having elements named `<joint>` and `<actuator>` makes sense for the simplest cases, where maybe there's only one of each. More complex transmissions should use more descriptive XML tags. The burden falls on the implementer of each parsing plugin. Note that this is already the case for PR2's transmissions ([example](https://github.com/PR2/pr2_common/blob/groovy-devel/pr2_description/urdf/forearm_v0/forearm.transmission.xacro)).

A more complex transmission where joints have more descriptive names and do not share the actuator's hardware interface would look like:

``` xml
<transmission type="transmission_interface/FingerTransmission" name="finger_trans">
  <proximal_joint name="f1_joint">
    <hardwareInterface type="EffortJointInterface"/>
    <mechanicalReduction>3</mechanicalReduction>
  </joint>
  <distal_joint name="f2_joint">
    <hardwareInterface type="JointStateInterface"/>
    <mechanicalReduction>2</mechanicalReduction>
  </joint>
  <actuator name="finger_motor">
    <hardwareInterface type="EffortJointInterface"/>
    <mechanicalReduction>50</mechanicalReduction>
  </actuator>
</transmission>
```

**Comment by jbohren** [comment] 2013-07-02 15:20
@adolfo-rt  I like the clarity of the last one. How about a slight modification:

``` xml
<transmission type="transmission_interface/FingerTransmission" name="finger_trans">
  <joint role="proximal_knuckle" name="f1_joint">
    <hardwareInterface type="EffortJointInterface"/>
    <mechanicalReduction>3</mechanicalReduction>
  </joint>
  <joint role="distal_knuckle" name="f2_joint">
    <hardwareInterface type="JointStateInterface"/>
    <mechanicalReduction>2</mechanicalReduction>
  </joint>
  <actuator name="finger_motor">
    <hardwareInterface type="EffortJointInterface"/>
    <mechanicalReduction>50</mechanicalReduction>
  </actuator>
</transmission>
```

We could also make the children tags more consistent by sticking either with attributes or text elements for parameters.

knuckle is a funny work when you write it out...

**Comment by davetcoleman** [comment] 2013-07-02 16:09
This seems like a good format. Could we start documenting this proposed format (and where it is used - ros_control) [here](www.ros.org/wiki/urdf/XML/Transmission). Maybe use these simple and complex use cases as examples.

**Comment by adolfo-rt** [comment] 2013-07-02 16:16
I like the example with roles specified separately!. I just read some recommendations on how to choose what should be an element and what an attribute, and this rule seemed fine to me:

_Use elements to describe data, use attributes to assign IDs to elements_

Following the above rule, the previous examples become

**Simple transmission**

``` xml
<transmission name="simple_trans">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="foo_joint"/>
  <actuator name="foo_motor">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>50</mechanicalReduction>
  </actuator>
</transmission>
```

**Finger**

``` xml
<transmission name="finger_trans">
  <type>transmission_interface/FingerTransmission</type>
  <joint name="f1_joint">
    <role>proximal_knuckle</role>
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>3</mechanicalReduction>
  </joint>
  <joint name="f2_joint">
    <role>distal_knuckle</role>
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>2</mechanicalReduction>
  </joint>
  <actuator name="finger_motor">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>50</mechanicalReduction>
  </actuator>
</transmission>
```

**Comment by davetcoleman** [comment] 2013-07-02 16:35
> _Use elements to describe data, use attributes to assign IDs to elements_

This is very SDF-like (Simulator Description Format)... which is now RML. URDF follows the "lots of attributes" philosophy, whereas SDF follows the above rule.

**Comment by adolfo-rt** [comment] 2013-07-02 17:01
Pardon my ignorance, but what is RML?

**Comment by davetcoleman** [comment] 2013-07-02 17:45
Robot Markup Language - its the proposed new name for SDF (not announced yet)

**Comment by jbohren** [comment] 2013-07-02 18:19
I think we should call then .hsu files.

@nkoenig @davetcoleman @hsu

**Comment by nkoenig** [comment] 2013-07-02 23:53
RML is withdrawn. SDF will be release in packages.osrfoundation.org, but never into ubuntu. A merger of SDF and URDF will begin soon.

**Comment by jbohren** [comment] 2013-07-03 00:17
> A merger of SDF and URDF will begin soon.

![manga_dbz_gogeta_fusion_01](https://f.cloud.github.com/assets/1253450/740452/f6987086-e375-11e2-95d4-5e37666ac47d.gif)

**Comment by davetcoleman** [comment] 2013-07-09 00:35
Ok, I'm implementing Adolfo's last version for `gazebo_ros_pkgs`. It mostly closely aligns to SDF's flavor of XML syntax, which is where discussion has been heading for the future of URDF.

```
<transmission name="simple_trans">
  <type>transmission_interface/SimpleTransmission</type>
  <joint name="foo_joint"/>
  <actuator name="foo_motor">
    <hardwareInterface>EffortJointInterface</hardwareInterface>
    <mechanicalReduction>50</mechanicalReduction>
  </actuator>
</transmission>
```

**Comment by davetcoleman** [comment] 2013-07-09 04:20
@adolfo-rt @jbohren I've implemented real better transmission parsing and moved the functionality out of gazebo_ros_pkgs and into transmission_interface. I don't want to send a pull request yet because I already have a pending one [here](https://github.com/ros-controls/ros_control/pull/81), but will you review my proposed method (using the previous comment's format)?

[Transmission parser](https://github.com/ros-controls/ros_control/blob/transmission_parsing/transmission_interface/src/transmission_parser.cpp) 

It certainly needs more work but I think its a good start. The class names `[Joint|Actuator]Data` were already taken so I created `[Transmission|Joint|Actuator]Info` that I modeled after [ControllerInfo](https://github.com/ros-controls/ros_control/blob/master/hardware_interface/include/hardware_interface/controller_info.h)

Finally, it would be great if someone fixed the [rosbuild side of CMakeLists.txt](https://github.com/ros-controls/ros_control/blob/transmission_parsing/transmission_interface/CMakeLists.txt#L13) because I don't remember how to use it.

You can see this new parser implemented in this [gazebo_ros_control](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/tranmission_parsing/gazebo_ros_control/src/ros_control_plugin.cpp#L278) branch.

**Comment by adolfo-rt** [comment] 2013-07-09 10:35
The code's looking good. Do you also have a plugin for the SimpleTransmission?. If so, I could take the code for a test drive. It would be a good excuse for me to get the rosbuild part done as well.

**Comment by davetcoleman** [comment] 2013-07-09 17:54
> Do you also have a plugin for the SimpleTransmission?

None of the code I have made so far actually loads transmission_interfaces, I only wrote the parser for our proposed transmission format. I'm using this parser in gazebo_ros_control to allow users to quickly get controllers working in Gazebo, but I've only laid the ground work for transmission usage. I don't personally have a use case for using transmissions in Gazebo at this moment. But you should be able to load a robot into Gazebo and use the effort_position_controller, no problem. Documentation should be ready in a few days.

**Comment by davetcoleman** [comment] 2013-07-09 17:56
FYI, the RML idea has been dropped in favor of a future (a year away) URDF version 2 format.

**Comment by davetcoleman** [comment] 2013-07-09 17:57
The pull request for this is now available https://github.com/ros-controls/ros_control/pull/84

**Comment by adolfo-rt** [comment] 2013-07-15 13:48
@davetcoleman if you are aware of an active SIG or public discussion focused on the URDF 2 effort, please let us know. I'd love to be part of the discussion.

**Comment by davetcoleman** [comment] 2013-07-15 18:09
There was a recent private skype meeting with a few people involved, but no work seems to have progressed since then. An empty bitbucket repo was created for the future work https://bitbucket.org/osrf/urdf/wiki/Home

**Comment by adolfo-rt** [comment] 2013-07-15 18:11
Thanks for the pointer.

**Comment by davetcoleman** [comment] 2013-07-19 00:36
Transmission parsing has been merged https://github.com/ros-simulation/gazebo_ros_pkgs/pull/80

This issue should be closed once the tranmission format is documented (\todo).

**Comment by davetcoleman** [comment] 2013-07-24 00:33
I have updated the URDF transmission documentation [here](http://ros.org/wiki/urdf/XML/Transmission), closing discussion.

**Closed as completed by davetcoleman** 2013-07-24 00:33 UTC

**Comment by adolfo-rt** [comment] 2013-07-24 08:32
Good stuff!. I'm trying to make some time this summer to implement plugins for the three existing transmission implementations. Let's hope this one pulls through.

**Comment by davetcoleman** [comment] 2013-07-24 16:31
Yea, right now the transmission parser doesn't actually do anything except load hardware interfaces for Gazebo.
