### ISSUE TITLE
Diff Drive plugin forces tf odom frame.

### ISSUE THREAD

**Issue by curranw** [ros-simulation/gazebo_ros_pkgs#213] opened 2014-06-30 17:20 UTC
For situations where the user needs to create their own simulated odom, like from laser scans, it conflicts with the diff drive odom tf frame published by gazebo.

http://answers.ros.org/question/175013/removingdeletingignoring-odom-tf-data/

**Comment by jonbinney** [comment] 2014-06-30 18:41
You could just use a launchfile to remap the odom that gazebo publishes to some other topic like odom_diff_drive, right?

**Comment by jonbinney** [comment] 2014-06-30 18:43
Actually there is a param that you can put in the sdf/urdf plugin called "odometryTopic" which you can just set to anything besides "odom"

**Comment by curranw** [comment] 2014-06-30 18:44
The issue is the TF, not the odom publisher. There is no way to kill a tf frame, and the odom tf connects to base_footprint automatically using the plugin. If you rename it, the tf frame is still there.

**Comment by jonbinney** [comment] 2014-06-30 18:49
Ah, I see. Makes sense.

**Comment by mikepurvis** [comment] 2014-09-12 04:16
Not sure if you're referring to `diff_drive_controller`, but it now supports disabling publishing the odom tf: https://github.com/ros-controls/ros_controllers/issues/118

**Comment by j-rivero** [comment] 2016-04-27 19:02
Looking at Mike's comment looks like we can close the issue. Please reopen if you think that the problem is still present.

**Closed as completed by j-rivero** 2016-04-27 19:02 UTC
