### ISSUE TITLE
spawn_model: seeding position of robot via roslaunch is not working correctly

### ISSUE THREAD

**Issue by bbrieber** [ros-simulation/gazebo_ros_pkgs#102] opened 2013-08-13 16:04 UTC
Hi,

I could not change the position of an robot when spawning them using roslaunch/rosrun.  The problem appears when the robot is defined in SDF with a <pose> element in the robots <model> element

it seems like the position is just appended to the old position

I could fix this for me by editing the updateSDFAttributes Function in the file gazebo_ros_api_plugin.cpp...

I changing the last lines there 

from:

```
TiXmlText* text = new TiXmlText(pose_stream.str());   
pose_element->LinkEndChild( text );
```

to:

```
TiXmlText* text = new TiXmlText(pose_stream.str());   
pose_element->Clear();
pose_element->LinkEndChild( text );
```

This is probably not the best solution because the pose will be overwritten with 0 values if no position is specified...

I'm currently not sure if position of robots are overwritten in general even if there is no position  specified when running the spawn_model script...

**Comment by davetcoleman** [comment] 2013-08-13 18:03
This is a duplicate of https://github.com/ros-simulation/gazebo_ros_pkgs/issues/93

**Comment by j-rivero** [comment] 2016-04-26 22:22
Duplicate.

**Closed as completed by j-rivero** 2016-04-26 22:22 UTC
