### ISSUE TITLE
ModelStates has no header (time stamp)

### ISSUE THREAD

**Issue by maxbader** [ros-simulation/gazebo_ros_pkgs#257] opened 2014-10-01 08:06 UTC
Hello

I was looking for ground truth data and I had the idea to use the /gazebo/model_states msg.
But this message does not include a time stamp which is important if the simulator does not run in real time. Or if somebody uses rosbag recorded data.
Would it be possible to enhance the msg or is there a special reason not to include a time stamp?

Greetings
Markus

**Comment by kev-the-dev** [comment] 2018-05-30 00:37
Duplicate of #535

**Comment by j-rivero** [comment] 2018-05-30 13:41
let's follow there. Thanks.

**Closed as completed by j-rivero** 2018-05-30 13:41 UTC
